### ISSUE TITLE
Add SignOut to README.md

### ISSUE THREAD

**Issue by jobvk** [f-miyu/Plugin.FirebaseAuth#12]
Please add how to SignOut in the  README.md File. Because I Don't Understand how to sign out.

**Comment by maurosampietro** [comment]
`CrossFirebaseAuth.Current.Instance.SignOut();`

By the way i think this does not signout from the provider you used to sign in (if you used facebook google or anything to login in firebase)

Maybe one of the developers can show us the best practice to signout from the provider we used and firebase at the same time

**Comment by maurosampietro** [comment]
Good to see you are doing well 2 years and 15 days later.
