### ISSUE TITLE
Pull-Request from: xamarindevelopervietnam

### ISSUE THREAD

**Issue by vhugogarcia** [f-miyu/Plugin.FirebaseAuth#17]
There is a PR created by @xamarindevelopervietnam I'm wondering if you plan to apply it to the plugin.

Thanks for this very cool wrapper.

**Comment by RichardSV15** [comment]
Much needed due to reference build errors with newer versions of other Firebase NuGets. It would be very very very much appreciated

**Comment by vincooys** [comment]
I second this, also for the other nugets since I'm using his Auth, Firestore, Crashlytics, and Analytics packages!

**Comment by angelru** [comment]
it is necessary
