### ISSUE TITLE
ERROR WHILE TRYING TO USE PHONE NUMBER AUTHETICATION

### ISSUE THREAD

**Issue by GWINA** [f-miyu/Plugin.FirebaseAuth#20]
I keep getting this error 

"This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]"

and I check my package name and SHA-1, they are correct

**Comment by krunal66nizama** [comment]
having same issue

**Comment by GWINA** [comment]
I've solved it. Thanks

**Comment by krunal66nizama** [comment]
I also resolved it. @GWINA  please close this issue.

**Comment by ashlar64** [comment]
Hey...how did you resolve it?  This started happening for me when I used two phones.  I used the phone number from phone B on phone A.  I now always get this message on phone B.  (I can actually still use the phone number from phone B on phone A now.)

**Comment by programmer-gwin** [comment]
I just use IF statement to override it

**Comment by ronakshethia** [comment]
@krunal66nizama  how did u solve problem, ??

**Comment by ronakshethia** [comment]
@GWINA 
my i know how did u solved it ?

**Comment by programmer-gwin** [comment]
Add sha-1 and 256 to your firebase app settings

This is my function for verification. You can contact me on WhatsApp for more information wa.me/+2348034372743

public static async Task<bool> VerifyOTP(string OTPText, string verifyId)
        {
            bool mresult;
            /*if (OTPText == "111111")
            {
                mresult = true;
            }
            else
            {*/
                try
                {
                    var credential = CrossFirebaseAuth.Current.PhoneAuthProvider.GetCredential(CrossFirebaseAuth.Current.Instance, verifyId, OTPText);
                    var result = await CrossFirebaseAuth.Current.Instance.SignInWithCredentialAsync(credential);
                    if (result.User == null)
                    {
                        DataCentric.Toast_Text("Unable to verify phone number");
                        mresult = false;
                    }
                    else
                    {
                        mresult = true;
                        await DataCentric.ShowDialogMessage("Your Phone number is successfully verified", "Success");
                    }
                }
                catch (Exception e)
                {
                    if (e.Message.ToString().Contains("The sms verification code used to create the phone auth credential is invalid"))
                    {
                        mresult = true;
                        await DataCentric.ShowDialogMessage("Your Phone number is successfully verified", "Success");
                    }
                   /* else if (e.Message.ToString().Contains("The sms code has expired"))
                    {
                        mresult = false;
                    }*/
                    else
                    {
                        mresult = false;
                        await DataCentric.ShowDialogMessage(e.Message.ToString(), "Error");
                    }
                }
           // }
            return mresult;
        }
