### ISSUE TITLE
Start of central directory not found

### ISSUE THREAD

**Issue by wrsullivan63** [f-miyu/Plugin.FirebaseAuth#31]
And, "Could not decompress the native framework 'FBLPromises.framework'...

After installing 'Plugin.FirebaseAuth' via Nuget I get this error when trying to debug the iOS app:
 
![Plugin FirebaseAuth Error](https://user-images.githubusercontent.com/70063992/115879186-63c52680-a417-11eb-8a35-514cf75c941e.png)

I've researched a few solutions and this one [https://forums.xamarin.com/discussion/186125/mtouch-error-mt1303-could-not-decompress-the-native-framework](url) at least gets rid of the errors, but when I run the app it crashes as soon as the launch screen appears.

Any thoughts on why it's crashing or even why it's getting the error in the first place?

**Comment by angelru** [comment]
If you are using Cloud Messaging, update to the latest version:
https://www.nuget.org/packages/Xamarin.Firebase.iOS.CloudMessaging/4.7.1

**Comment by wrsullivan63** [comment]
Thank you!  That did the trick.
