### ISSUE TITLE
SignInWithGoogle

### ISSUE THREAD

**Issue by robertmaxted** [f-miyu/Plugin.FirebaseAuth#38]
Hi, How can I sign in with google without using reactiveUI and Prism?? I'm really struggling to get this working. Can you please give me some advice or pointers please? 

Kind regards,
Rob

**Comment by angelru** [comment]
With this plugin, GoogleClientPlugin and traditional MVVM works perfect, also,also, that question has to be asked in the xamairn forum.

https://github.com/CrossGeeks/GoogleClientPlugin

**Comment by robertmaxted** [comment]
Thanks angelru :)
